# -*- coding: utf-8 -*-
"""Editorial content of the Flores Race course brochure.

Every *number about the course* (kilometres, climbing, unpaved share, hike-a-bike) is injected
by pipeline/build_brochure.py from exports/gpx/manifest.json -- never typed here. What lives here
is prose, place descriptions and the honest framing. Facts about places come from the curated
data in data/ and from a desk-research pass (September 2026); where a fact rests on a single
source or on a travel snippet, the wording says "reported" or "said to". Dates matter for the
hazards: they are stated and must be re-checked before race week.

Image references are slugs of docs/brochure/img/sat/<slug>.jpg (Sentinel-2 true-colour crops);
maps and profiles are picked up by id.
"""

CONTENT = {
    "meta": {
        "title": "Flores Race",
        "subtitle": "A self-supported traverse of the island of fire, Labuan Bajo to Larantuka",
        "edition": "Course concept brochure · September 2026",
        "status": "Concept status. Every line in this document is routed over the mapped track network and has not yet been ridden or scouted by the team. It is a proposal for stakeholders and for the first scouting season, not a decision.",
        "repo": "github.com/technicaloutdoor/Flores-Race",
    },
    "cover": {
        "kicker": "West to east · single stage · self-supported",
        "tagline": "Across Flores on farmers' tracks, over the volcanic spine and back to both coasts: a course concept in ten sections, with its optional loops, its hazards and the villages that will host it.",
        "image": "inerie-bena",
        "image_caption": "Cover: Inerie and the Ngada villages, Copernicus Sentinel-2.",
    },
    "idea": {
        "heading": "The idea in one page",
        "paragraphs": [
            "Flores is only about 360 kilometres long, but it is a wall of volcanoes with two coasts. The paved Trans-Flores highway needs roughly twice that distance to cross it because it has to. A race that keeps leaving the highway to climb over the spine on farmers' tracks, drop to a forgotten coast and climb back again reaches well over 1,300 kilometres and more than 30,000 metres of climbing, most of it unpaved and a meaningful share of it on foot with the bike.",
            "The course runs west to east, from Labuan Bajo, the Komodo gateway with international flights and a sunset harbour, to Larantuka, the Portuguese-Catholic town under Ile Mandiri at the island's eastern tip. West to east because the dry-season wind blows from the east-south-east, so riders earn every kilometre, and because the island's story reads that way: from Komodo and the Manggarai highlands to Ngada's megalithic villages, the Lio country around Kelimutu, the ikat weavers of Sikka and the Catholic east.",
            "The format is borrowed deliberately from the Silk Road Mountain Race: one stage, fixed route, no outside support, mandatory checkpoints, a time limit of about two weeks, a dry-season window from late June to September. Some checkpoints are cultural: riders sign in at a village that has agreed to host the race, and the village earns from it. That agreement is the point, not a detail.",
        ],
        "rules": [
            ("Prefer the small track", "A farm track, a cattle path across savanna or a village-to-village footpath over a ridge always beats a paved road, even a scenic one."),
            ("Touch both coasts, repeatedly", "Every section that can cross the spine, does. The island is narrow; the course uses that."),
            ("Hike-a-bike is a feature, and it is honest", "Where the bike is carried, the section says for how many kilometres, and scouts will have walked it."),
            ("Every section has a reason", "A volcano, a village, a beach, a piece of history. If a stretch has no story, it is a link, and links are kept short."),
            ("Villages are hosts, not scenery", "Wae Rebo, Bena, Gurusina, Luba, Tololela, Wologai, Nggela and the others receive guests with protocol. No rider passes before the village council has agreed; where agreement is not possible, the route goes around."),
            ("Respect the hazard zones", "Active volcanoes define exclusion radii the route honours on race day, with a pre-agreed reroute and an abort rule."),
            ("Resupply is sparse but never impossible", "No rider should be more than about 120 kilometres from food and water. The north coast and the Nagekeo interior need particular care."),
        ],
    },
    "glance": {
        "heading": "The course at a glance",
        "intro": "Ten narrative sections chain 37 anchors from the Komodo gateway to the Portuguese east. The numbers below are computed from the routed geometry with SRTM elevation, the pipeline's smoothing and a 10-metre climbing threshold; they will move once scouts bring back GPS tracks, and Ride with GPS will show slightly different climbing figures from its own terrain model.",
        "legend": "Main course in vermilion. Optional loops and alternatives dashed, each in its own colour throughout the brochure.",
    },
    "rwgps": {
        "heading": "Riding it on Ride with GPS",
        "paragraphs": [
            "The whole course exists as GPX files in the repository, under exports/gpx: the main traverse (with and without points of interest), the Ultra and Ultra+ variants, one file per section and one per optional loop or alternative. Ride with GPS imports them directly and keeps every farm track exactly as routed; it recomputes elevation, surface and cue sheet from its own data.",
            "Import is two minutes per file: open the route planner (ridewithgps.com/routes/new), click Import in the Route panel, choose Upload File, pick a GPX, Add to Planner, name it, set it private while the course is a concept, Save. Put everything in a collection called Flores Race so the team finds it in one place. The dashboard's Upload page takes several files at once; choose Save as Route, not Add to My Activities.",
            "The maps in this brochure are rendered by the project's own pipeline from the same data (SRTM relief, roads and coastline from OpenStreetMap via Overture Maps). They are not planner screenshots: the environment this brochure was produced in could not reach Ride with GPS. Once the routes are in the planner, its screenshots can complement these maps; the geometry is identical.",
        ],
    },
    "sections": [
        {
            "id": "sec-01-komodo-mbeliling",
            "order": 1,
            "title": "Komodo gate and the Mbeliling forest",
            "subtitle": "Leaving the tourist town for the first farm tracks",
            "anchors_line": "Labuan Bajo → Mbeliling forest → Sano Nggoang → Werang",
            "hero": "sano-nggoang",
            "lede": "The race starts in the one place every rider already half-knows, and turns its back on it within a few kilometres.",
            "story": [
                "Labuan Bajo is dragons, dive boats and an international airport: the busiest harbour in the region, fully geared, expensive in August. The course leaves the waterfront and climbs into the Mbeliling forest reserve, roughly 15,000 hectares of Important Bird Area rising to about 1,275 metres, the highest ground in West Manggarai. It holds all four birds found only on Flores: the Flores hanging parrot, the Flores monarch, the Flores crow and the Flores scops owl. This is the unglamorous, verifiable version of remote, and it is the first test of the course's first rule: the farm track through the forest rather than the highway that skirts it.",
                "Two waterfalls give the section its texture. Cunca Wulang is a river canyon with deep pools and cliff-jumping spots near Wersawe, about 30 kilometres from town, run informally by the village for a small fee: spectacular and easy, no dismount needed. Cunca Rami, a 30-metre fall deep in the forest near Wae Lolos, is a real jungle hike-a-bike whose exact position the desk data itself admits is unresolved, with local sources and the terrain model disagreeing by 400 metres of altitude. That is precisely why this section opens the first scouting season.",
                "The payoff is Sano Nggoang: an elliptical caldera lake at about 750 metres, reported as the largest crater lake in East Nusa Tenggara and among the deepest volcanic lakes anywhere, with solfataras and hot springs steaming on its south-eastern shore below the 903-metre Wai Sano volcano. Most Komodo visitors never see it. The section ends eight kilometres north at Werang, the sub-district capital: a parish church, a boarding school, a police post, a handful of kiosks. The first honest resupply of the race.",
            ],
            "places": [
                {"name": "Sano Nggoang and Wai Sano", "image": "sano-nggoang", "text": "The caldera lake from orbit: the ellipse of dark water inside the Wai Sano complex. The lakeshore village of Wae Sano has been the centre of a contested geothermal project since Flores was designated a national geothermal priority; two international financiers withdrew over consent failures with the Indigenous Manggarai community. The race should know this and take no side."},
                {"name": "Labuan Bajo bay", "image": "labuan-bajo-bay", "text": "The start line: harbour, liveaboards, the airport on the hill. Dry season here runs May to September; August is the driest and the busiest month."},
                {"name": "The Komodo gateway", "image": "komodo-gateway", "text": "Context, not course: Komodo and Rinca lie a boat ride west. The national park moved to a daily visitor quota with mandatory pre-booking in 2026; it is the reason the start town is crowded, and the reason its name carries."},
            ],
            "practical": {
                "water": "Reliable only in Labuan Bajo. Unreliable at the lake and in Werang; carry from the start.",
                "resupply": "Full in Labuan Bajo (supermarkets, ATMs, the region's only hospital). Kiosks in Werang. Nothing on the forest track.",
                "sleep": "Hotels in Labuan Bajo; small homestays at the lake and in Werang, capacity for a race field unconfirmed; an ecolodge in the Mbeliling landscape.",
                "protocol": "No cultural checkpoint in this section. Village-collected fees at the waterfalls (reported IDR 30,000 to 100,000 at Cunca Wulang depending on guiding).",
                "hazards": "River pools and cliff jumps at Cunca Wulang (informal site, no lifeguard); geothermal features at the lake are not bathing spots; a documented saltwater-crocodile fatality on West Manggarai's coast means no wading in estuaries.",
            },
            "scouting": [
                "Is the Mbeliling forest track rideable end to end, or does it need dismounts near the two waterfalls?",
                "Fix Cunca Rami's position by GPS: desk position and terrain elevation disagree by about 400 metres.",
                "Homestay capacity at Sano Nggoang and Werang for race-week volume.",
            ],
            "options": [],
        },
        {
            "id": "sec-02-wae-rebo-south-coast",
            "order": 2,
            "title": "Wae Rebo and the south coast of Manggarai",
            "subtitle": "The flagship cultural checkpoint, reached the only way it can be",
            "anchors_line": "Werang → Dintor → Denge → Wae Rebo (hike-a-bike) → Todo → Iteng",
            "hero": "wae-rebo-valley",
            "lede": "No road has ever reached Wae Rebo. Every visitor arrives the way the village's own rice and roof thatch do: on foot.",
            "story": [
                "From Werang the course drops off the plateau to a stretch of south coast almost no visitor sees. Dintor is a white-sand beach village in Satar Ruwuk with Pulau Mules offshore and no services; Denge, a few kilometres inland, is the last village a vehicle reaches and the trekkers' staging post, with a rice-field homestay of about nine rooms. Beyond Denge everything moves on foot or on someone's back.",
                "The Wae Rebo trail is about eight kilometres and 700 metres of climbing through rainforest, two and a half to three hours for a trekker, considerably more with a loaded bike. At the top stand seven cone-roofed mbaru niang around a ceremonial ground at about 1,100 to 1,200 metres: five floors of wood, bamboo and palm thatch built without nails, rebuilt by the community in the traditional form rather than in tin, which won the village UNESCO's Asia-Pacific Award for Cultural Heritage Conservation in 2012. Oral tradition names a founder, Empo Maro, who came from Minangkabau in Sumatra guided by a dream. Visitors are received with the Wae Lu'u welcome ceremony, sleep inside the houses and pay a set contribution; roughly IDR 350,000 for an overnight package and a IDR 50,000 ceremony donation are the figures currently reported, and there is no visitor quota. None of that can simply be inherited by a race: the village council's agreement is the precondition for this checkpoint.",
                "The onward trail from Wae Rebo towards Todo is the section's open question; no public trekking source describes it, and every visitor account goes back down to Denge. The course therefore carries an out-and-back alternative. Todo, reached by road, is where Manggarai tradition places the seat of its old kingdom and its oldest standing mbaru niang, the drum house Niang Todo: the same architecture as Wae Rebo, with the origin story attached, and elders who receive guests with a guest book and a small donation. The section ends at Iteng, the Satar Mese sub-district capital on the coast: a market, a parish, a health centre, the first real food after two remote days.",
            ],
            "places": [
                {"name": "The Wae Rebo valley", "image": "wae-rebo-valley", "text": "Forest, ridges and the clearing at the head of the valley. The seven houses are said to stand for the seven peaks around them. The trail is landslide-prone in the wet season; 2025 and 2026 traveller reports describe intermittent closures and bamboo-bridge repairs."},
                {"name": "Todo", "image": "todo-village", "text": "A short climb off the Ruteng road. No hike-a-bike here; the deep-history counterweight to the trek."},
            ],
            "practical": {
                "water": "Unreliable throughout. Denge and Wae Rebo have water for guests, not for a field of riders; carry full capacity from Werang.",
                "resupply": "Minimal: kiosks in Denge and Dintor, nothing on the trail, a market at Iteng.",
                "sleep": "Homestays in Denge and inside the mbaru niang at Wae Rebo (by agreement); nothing at Dintor or Todo; Iteng unconfirmed.",
                "protocol": "Cultural checkpoint. Welcome ceremony, guest book, set contributions; photography of interiors and ceremonies by permission. A race-specific agreement with the council is required before a single rider passes.",
                "hazards": "Steep, slippery porters' path with steps; landslides after rain; heat on the coast, cold at the village at night.",
            },
            "scouting": [
                "Is the Wae Rebo onward trail passable with a loaded bike, or is the out-and-back the default?",
                "Terms and timing of a Wae Rebo checkpoint and a Todo visit with the village councils.",
                "Field GPS fixes for Dintor and Denge; both are still desk placements.",
            ],
            "options": ["opt-wae-rebo-out-and-back"],
        },
        {
            "id": "sec-03-manggarai-highlands",
            "order": 3,
            "title": "Manggarai highlands",
            "subtitle": "From a warm coast to a cold cathedral town, the island's roof and its oldest human story",
            "anchors_line": "Iteng → Ruteng → Ranamese / Poco Ranaka → Liang Bua",
            "hero": "lingko-cancar",
            "lede": "Roughly 1,100 metres of climbing separate the coast at Iteng from Ruteng's cool air, and the section only gets higher from there.",
            "story": [
                "Ruteng sits at about 1,200 metres: a compact, walkable Catholic hill town of red roofs and rice terraces, sixteen to twenty-four degrees, the best full resupply of the whole west (a central market, a hospital, banks, many homestays). Its cathedral, consecrated in 2002, seats 2,500; the Golo Curu hill above the town carries a Marian grotto and the panorama. On the most Catholic island of Indonesia's most Catholic province, this is where the contrast with the customary-law villages just behind the riders is sharpest.",
                "A short detour west of town, the Cancar rice fields resolve from a viewing hill into a spider's web. This is lingko, the Manggarai communal land system: a field divided outward from a centre point, the lodok, into wedges whose width reflects each family's standing, with planting and harvest rites at the centre. It is the one spectacular view on the whole course that costs no hike-a-bike at all, for a fee of a few thousand rupiah and a ten-minute walk.",
                "South-east of Ruteng rises the roof of Flores: Poco Mandasawu, the island's highest point at about 2,370 metres, and Poco Ranaka with its 1987 lava dome Anak Ranakah, inside the 32,000-hectare Ruteng Nature Recreation Park. The course skirts this massif on the way to Ranamese, a small, 21-metre-deep crater lake at 1,220 metres with a warung at the car park: the highest and coldest rest stop of the race, with the Cunca Rede waterfall a short trail away. Then it descends north to Liang Bua, a single wide limestone chamber where, in September 2003, a joint Indonesian-Australian team found the near-complete skeleton of a one-metre-tall human relative, Homo floresiensis. A 2016 re-dating put the youngest bones at 60,000 to 100,000 years, and at Mata Menge in the So'a basin the lineage reaches back about 700,000 years. The cave is still used by the local community for ceremonies; a guide meets visitors at the entrance, and a small museum shows casts.",
            ],
            "places": [
                {"name": "The Cancar lingko", "image": "lingko-cancar", "text": "The spider-web fields from orbit. Sources put Cancar 17 to 25 kilometres from Ruteng; the viewing hill stands beside a telecoms tower."},
                {"name": "Ruteng", "image": "ruteng-highlands", "text": "The highland capital on the Trans-Flores. Full resupply, RSUD Ruteng hospital, many homestays; cool nights."},
                {"name": "Ranamese", "image": "ranamese-lake", "text": "Five hectares of still water at 1,220 metres, sixteen kilometres from Ruteng. The only resupply between Ruteng and Liang Bua is the warung here."},
                {"name": "Liang Bua", "image": "liang-bua", "text": "The valley of the hobbit cave, fourteen kilometres north-west of Ruteng. Entrance fees are reported inconsistently (IDR 30,000 to 80,000); confirm on the ground."},
            ],
            "practical": {
                "water": "Reliable in Ruteng; unreliable at Iteng, Ranamese and Liang Bua. Nothing on the massif.",
                "resupply": "Full in Ruteng. A warung at Ranamese. Minimal at Liang Bua.",
                "sleep": "Hotels and homestays in Ruteng (Hobbit Hill homestay is on the road towards Liang Bua); nothing at the lake or the cave.",
                "protocol": "Liang Bua is a working heritage and ceremonial site: follow the guide, no touching the excavation. Cancar viewpoint fee reported at IDR 15,000 to 30,000.",
                "hazards": "Sustained climb from sea level to 1,200 metres in heat, then cold and cloud at altitude; exposed volcanic trail if the massif is crossed on foot.",
            },
            "scouting": [
                "Is there a farm-track alternative to the paved road over the Ranamese pass?",
                "A more direct track between Ranamese and Liang Bua than the current chain, which doubles back near Ruteng?",
                "Which summit elevations to print for Poco Mandasawu and Poco Ranaka: sources conflict by up to 200 metres.",
            ],
            "options": ["opt-manggarai-timur-interior"],
        },
        {
            "id": "sec-04-north-coast",
            "order": 4,
            "title": "The forgotten north coast",
            "subtitle": "Savanna, lontar palms, small ports, and the water question that will define the race",
            "anchors_line": "Liang Bua → Reo → Pota → Riung",
            "hero": "pota-savanna",
            "lede": "Dry, hot, sparsely populated and beautiful: the section the concept names as its defining unknown.",
            "story": [
                "Reo is an old north-coast market town with a mosque and a church side by side, a bank, a health centre and a Dutch-era cannon on the hill above the bay; its working harbour, Kedindi, a few kilometres west at the river mouth, is talked of as the province's next big export port. Local history traces the first settlement to the Bima sultanate's traders; under the Dutch, the Manggarai resistance leader Motang Rua was shipped through Reo into exile. It is the last full resupply before the driest stretch of the course.",
                "East of Reo the coast becomes lontar-palm savanna and wide bays with almost nobody in them. The desk data called this corridor undocumented; current sources say a road exists the whole way, paved from Ruteng to Reo and Pota, then rough, potholed and periodically cut by landslides between Pota and Riung via Buntal, Golo Lijung and Dampek. The honest open question is not whether a track exists but how good it is with a loaded bike, and above all where the water is. In August 2026 the district was under an emergency dry-season water-trucking operation covering Pota, Nangambaur, Golo Lijun and posts across Sambi Rampas and Borong. Water here is not a hypothesis; it is the constraint.",
                "Pota, the Sambi Rampas sub-district capital, is the midpoint and the junction where the Manggarai Timur interior loop rejoins the coast. Riung is the reward: a small fishing port at the gate of the Seventeen Islands Marine Park, more than twenty coral islets reached by hired boat, with a colony of thousands of flying foxes that lifts off Pulau Ontoloe at dusk, snorkelling over reef, and half a dozen simple guesthouses. Park entrance is reported at about IDR 100,000; a day boat for a small group around IDR 400,000 per person.",
            ],
            "places": [
                {"name": "The savanna between Reo and Pota", "image": "pota-savanna", "text": "Bays, dry riverbeds and palm savanna from orbit. Early departures, shade at midday and a mandatory water-carry rule belong to this section."},
                {"name": "Reo and the Kedindi harbour", "image": "reo-north-coast", "text": "The Wae Reo river mouth and the port. Paved road south to Ruteng; an active, not sleepy, waterfront."},
                {"name": "Riung and the Seventeen Islands", "image": "riung-17-islands", "text": "Islets, reef and mangrove north of the village. The Timor monitor lizard lives here; a locally named larger monitor, the mbou, is reported at Torong Padang, thinly sourced."},
            ],
            "practical": {
                "water": "The constraint of the race. Reliable in Reo only; unreliable at Pota and Riung; villages between were on emergency trucking in August 2026. Mandatory carry capacity; planned water points only if unavoidable.",
                "resupply": "Basic in Reo and Pota (kiosks, health posts), basic in Riung with guesthouse kitchens. Nothing in between.",
                "sleep": "A homestay in Reo; nothing confirmed at Pota; several guesthouses in Riung (reported IDR 150,000 to 350,000).",
                "protocol": "No cultural checkpoint. Marine park fee if riders take a boat. Mosque and church etiquette in Reo.",
                "hazards": "Heat and dehydration; rough, landslide-prone road east of Pota; river mouths and mangroves are crocodile country, no wading at dawn or dusk.",
            },
            "scouting": [
                "Ride the Pota to Riung road end to end: rideable as a continuous line, or portage sections?",
                "Where exactly is water between Reo and Riung in August, and which villages can host a water point?",
                "Which island carries the flying-fox colony: Ontoloe per current sources, Tembang per the curated data?",
            ],
            "options": ["opt-manggarai-timur-interior"],
        },
        {
            "id": "sec-05-ngada-inerie",
            "order": 5,
            "title": "Ngada: megaliths under Inerie",
            "subtitle": "Cultural checkpoints under a near-perfect volcano",
            "anchors_line": "Riung → Soa (Mengeruda hot springs) → Bajawa → Bena → Aimere",
            "hero": "inerie-bena",
            "lede": "The villages beneath Inerie orient their ancestor shrines towards its slope. The mountain is a presiding relative, not scenery.",
            "story": [
                "From the coast at Riung the course climbs to the Bajawa plateau, eleven hundred metres up, with a stop halfway that riders will remember: the Mengeruda hot springs at Soa, warm river pools in a jungle valley near the airstrip, ticketed at a few thousand rupiah and open eight to six. Bajawa itself is a cool highland capital with a market, hotels and ATMs, the last full service before four days of minimal-service villages. Wolobobo hill above the town is the plateau's best sunrise: mist pooling below, Inerie's silhouette, Ebulobo far to the east on a clear morning.",
                "Nineteen kilometres south, Bena is the reference image of Ngada culture: two rows of thatched houses on a narrow ridge framing a stone-terraced square of megalithic tombs and paired ngadhu and bhaga, a carved post for each clan's male ancestor and a small thatched house for the female one, nine pairs for nine clans. Guests sign a book and leave a donation (IDR 10,000 to 25,000 is commonly cited). Luba, a few hundred metres away, has four clans and carved animal motifs and far fewer visitors; Tololela, on a steep hillside at 650 metres, is where travellers actually sleep in the village; Gurusina, on Inerie's south-eastern flank, was rebuilt in traditional materials after a fire on 13 August 2018 destroyed 27 of its 33 houses while the village watched a football match. Each has its own council, and each checkpoint needs its own agreement. Reba, the Ngada new-year festival of yams and ancestors, runs from late December into January: spectacular, and outside the race window.",
                "Inerie is 2,245 metres, the highest peak in Ngada, dormant since a smoke plume in 1911, and climbed from Watumeze in three to four hours over loose scree with no shade and more than 1,500 metres of gain. The main course crosses its shoulder from Bena down to the coast at Aimere, five to ten kilometres of steep, loose hike-a-bike that nobody has yet done with a loaded bike. The Inerie full circuit is the alternative: Bena, Gurusina, the wild southern slope down to the sea at Sewowoto, then the coast road west. Aimere closes the section as a working port: the ferry to Sumba and Kupang, and household stills turning lontar palm sap into arak over open fires.",
            ],
            "places": [
                {"name": "Inerie and Bena", "image": "inerie-bena", "text": "The cone from orbit, Bena and Luba on the ridge to its north-east, Gurusina on the south-eastern flank, the sea to the south. The shrines in every village square face the slope."},
                {"name": "Soa and the Mengeruda springs", "image": "soa-mengeruda", "text": "The Soa basin, the Turelelo airstrip and the warm river at Piga. Also the region of the Mata Menge fossil site, where the Homo floresiensis lineage reaches back about 700,000 years."},
                {"name": "The Aimere coast", "image": "aimere-coast", "text": "Lontar groves, the ferry port, the arak coast. The exact pier position still needs a field fix."},
            ],
            "practical": {
                "water": "Reliable in Bajawa and Soa; unreliable in every village under the volcano and at Aimere.",
                "resupply": "Full in Bajawa. Minimal in Bena, Luba, Tololela, Gurusina; basic in Aimere.",
                "sleep": "Hotels in Bajawa; homestays reported at Tololela and Gurusina, Bena may be day-visit only; homestay at Aimere.",
                "protocol": "Cultural checkpoints. Greet the elders first, guest book, donation, ask before photographing people or houses, no naked flames near thatch. Council agreements required for Bena, Luba, Tololela and Gurusina.",
                "hazards": "Loose volcanic scree and exposure on the Inerie shoulder; cloud builds by mid-morning; no water on the mountain; fire risk in thatched villages.",
            },
            "scouting": [
                "Is the Bena-side Inerie shoulder descent safe with a loaded bike?",
                "Which villages will host checkpoints, under what terms, and does Bena offer beds at all?",
                "The Sewowoto coast and the Gurusina descent for the full-circuit option: rideable, walkable, water?",
            ],
            "options": ["opt-inerie-circuit"],
        },
        {
            "id": "sec-06-ebulobo-nagekeo",
            "order": 6,
            "title": "Ebulobo and the Nagekeo plains",
            "subtitle": "A steaming seminary, a live volcano farmed to the treeline, and the island's rice bowl",
            "anchors_line": "Aimere → Mataloko / Wogo → Boawae → Mbay",
            "hero": "ebulobo-boawae",
            "lede": "Back up to the plateau, round the cone of Ebulobo, and down the Aesesa valley to the north coast.",
            "story": [
                "Mataloko is the section's postcard: a whitewashed colonial-era minor seminary, St Yohanes Berchmans, silhouetted against the steam of a geothermal field of more than twenty hot springs, fumaroles and mud pools across a thousand hectares. The springs are a real rider amenity; the geothermal plant behind them, operating since 1998, is also a live local-goodwill issue in the surrounding villages, which is worth knowing before any checkpoint or filming near it. Wogo, a sealed side road away, has nine ngadhu-bhaga pairs in a U-shaped compound and, a kilometre's walk further, the abandoned original site of old Wogo where megalithic tombs still stand in the grass and still serve ceremonies.",
                "Boawae sits directly on the north-western slope of Ebulobo, an active 2,124-metre stratovolcano first recorded erupting in 1830, monitored from an observation post at Ekowolo, farmed almost to the treeline. A summit hike from Mulakoli takes about two hours of forest and a final scramble, with a village-mandated guide. Boawae is also the home of Etu, Nagekeo's ceremonial one-handed boxing, fought in palm-fibre gloves as part of the harvest-thanksgiving cycle in June and July: a living ritual, not a show, and one whose dates may fall inside the race window.",
                "The Aesesa valley then opens into the largest rice plain of Flores, irrigated, flat and hot, and Mbay, the Nagekeo capital, with hotels and the last certain full resupply before the waist crossing. Its port, Marapokot, eight kilometres north, runs ferries to Palue and towards Maumere. Two alternatives shorten this section: straight from Boawae over to the south coast at Nangaroro, or the whole way along the remote south coast from Aimere to Nangaroro, skipping the plateau altogether.",
            ],
            "places": [
                {"name": "Ebulobo and Boawae", "image": "ebulobo-boawae", "text": "The cone from orbit, the town on its shoulder, the Trans-Flores at its foot. A magnitude 7.7 earthquake on 15 August 2026 triggered landslides near the summit, per Indonesia's geological agency, with no rise in volcanic activity."},
                {"name": "Mbay and the Aesesa plain", "image": "mbay-aesesa-plain", "text": "The rice bowl of the island: irrigation channels, causeways between paddies, the coast beyond. Nagekeo as a whole is dry; the plain is the exception."},
            ],
            "practical": {
                "water": "Reliable at Mataloko, Boawae and Mbay; unreliable at Aimere and between the villages.",
                "resupply": "Basic at Mataloko and Boawae; full at Mbay.",
                "sleep": "Guesthouse at Mataloko, homestay at Boawae, hotels at Mbay (reported IDR 150,000 to 250,000).",
                "protocol": "Wogo: council permission for a group visit, modest contribution. The seminary is a working institution: ask before photographing inside its grounds. Etu is attended only with adat consent.",
                "hazards": "Ebulobo alert level (Level I as of the last public bulletins found) and earthquake aftershock advisories to be re-checked before race week; scalding ground at the geothermal field; heat on the shadeless plain.",
            },
            "scouting": [
                "Ridge-crossing footpaths between the coasts in Nagekeo: the real scouting work of this section.",
                "Mbay's town-centre coordinate is still a desk estimate.",
                "Exact Etu dates for the race year, and whether the race should meet or avoid them.",
            ],
            "options": ["opt-boawae-nangaroro-direct", "opt-south-coast-aimere-nangaroro"],
        },
        {
            "id": "sec-07-blue-stone-coast",
            "order": 7,
            "title": "The blue-stone coast to Ende",
            "subtitle": "Across the island's waist to a beach made of turquoise pebbles and the town where a republic was imagined",
            "anchors_line": "Mbay → Nangaroro → Penggajawa → Ende",
            "hero": "penggajawa-blue-stone",
            "lede": "The narrowest part of Flores is short on the map and hard on the ground.",
            "story": [
                "The crossing from the north-coast plain at Mbay to Nangaroro on the south coast is the least verified link of the whole course: a computed candidate over the island's waist, mostly unpaved, with about 1,700 metres of climbing packed into fifty-odd kilometres, and no source that confirms the specific line. It is scouting-priority terrain, not a confirmed road. Nangaroro itself is a farming and fishing district of grey-stone beaches; a homestay, unreliable water, and the last bed before Ende.",
                "Twenty-five kilometres before Ende comes the section's headline: Penggajawa, a beach made not of sand but of smooth blue-green volcanic pebbles, called Batu Biru or Batu Hijau depending on whether they are wet. Local accounts differ on whether the stones come down the rivers from the mountains or up from the seafloor; what is certain is that residents hand-sort them to size for a small export trade, without machinery. Nobody sleeps here; it is a stop and a photograph.",
                "Ende is the largest town of central Flores, about 90,000 people under the 637-metre Iya volcano, with a hospital, an airport, hotels, the Mbongawani market where traders wear woven sarongs, and the strongest history hook of the middle course. Sukarno lived here in Dutch-imposed exile from January 1934 to 1938, in a plain 1927 house on Jalan Perwira that has been a museum since 1954, its meditation room and library largely unchanged, free entry by donation. On the seafront a five-branched breadfruit tree, planted in 1980 to replace the original, marks where he is said to have worked out the five principles of the Pancasila while looking at the sea. Full resupply, and the gateway to the signature section.",
            ],
            "places": [
                {"name": "Penggajawa", "image": "penggajawa-blue-stone", "text": "The blue-stone coast between Nangapanda and Ende from orbit; the Bajawa to Ende road hugs the shore. The stones show their colour best wet."},
                {"name": "Ende under Iya", "image": "ende-iya", "text": "The town, its airport and the southern peninsula with Iya's crater. PVMBG held Iya at Level II with a two-kilometre stay-away radius through at least June 2026 after a rise to Level III in late 2024."},
            ],
            "practical": {
                "water": "Reliable at Mbay and Ende only. Carry for the waist crossing.",
                "resupply": "Full at both ends; basic at Nangaroro; nothing at Penggajawa.",
                "sleep": "Hotels at Mbay and Ende; homestay at Nangaroro; nothing at Penggajawa.",
                "protocol": "None specific. The exile house is open 08:00 to 16:00; donation box.",
                "hazards": "Unverified track on the crossing; heat on the exposed coast road; Iya's alert level to be checked before any decision on the southern peninsula.",
            },
            "scouting": [
                "Ridge-crossing footpaths across the Mbay to Nangaroro waist: ground truth needed.",
                "Which line to Nangaroro: over the waist from Mbay, direct from Boawae, or the south coast from Aimere?",
                "Water and beds at Nangaroro and Penggajawa for a race field.",
            ],
            "options": ["opt-boawae-nangaroro-direct", "opt-south-coast-aimere-nangaroro"],
        },
        {
            "id": "sec-08-kelimutu-lio",
            "order": 8,
            "title": "Kelimutu and the Lio country",
            "subtitle": "The signature section: adat villages, rice terraces, three coloured lakes at dawn, the weavers, the white beaches",
            "anchors_line": "Ende → Detusoko → Moni → Kelimutu → Wolojita → Nggela → Koka",
            "hero": "kelimutu-lakes",
            "lede": "The only place on the course where riders are required to stop. In Lio belief it is where souls go.",
            "story": [
                "Out of Ende the road climbs past Wolotopo, a Lio village stepped up a steep hillside above the sea where households still weave and keep their ceremonial houses, into cool highland farmland. The Detusoko terraces at 800 metres are compared with Ubud's and see a fraction of the visitors; Wologai, higher still at about 1,045 metres, is an 800-year-old circular village around a stepped stone ceremonial ground, rebuilt in traditional form after a 2012 fire, where elders receive guests with betel and a guest book and the annual Nggua Ria thanksgiving is still held. Moni, one road of homestays and warungs at the foot of the mountain, is where riders sleep before the dawn climb.",
                "Kelimutu's three crater lakes sit at 1,639 metres on one summit inside a 5,300-hectare national park: Tiwu Ata Mbupu, the lake of the old people; the middle lake of young men and maidens; Tiwu Ata Polo, the bewitched lake. Each shifts colour independently over months as the hydrothermal chemistry changes; in July 2026 all three were shades of green. The Lio hold that the lakes sort the dead by how they lived, and every 14 August the mosalaki process to the rim for Pati Ka, feeding the ancestral spirits with red rice, pork, betel, tobacco and palm wine before a circle dance. The park opens at five in the morning; the foreign entrance fee is reported at IDR 150,000 on weekdays and 225,000 at weekends. Standing rules apply regardless of alert level: no approach to the rims, above all at the middle crater, no camping, dawn only. PVMBG recorded a rise in the middle lake's temperature through June 2026 and a January 2026 wall slide, and kept the volcano at Level I; the status is re-checked the week before the race, never assumed.",
                "South of the mountain the course drops through the Lio weaving villages. Jopu and Wolojita share the back-strap loom tradition but now mostly dye with chemicals; Nggela, on a coastal ridge at 180 metres reached by a single-track road, is the village that defines Lio ikat, almost every household at a loom, its cloth collected internationally, and even here truly natural morinda-root dyeing, a two-year process, is rare and demonstrated rather than routine. Nggela is a named cultural checkpoint in the concept and needs council agreement like Wae Rebo. The section ends on white sand: Koka's twin coves below Wolowiro, two kilometres of unpaved spur through cocoa forest with a small private toll, and Paga's simple beachside warungs on the highway.",
            ],
            "places": [
                {"name": "The three lakes", "image": "kelimutu-lakes", "text": "Kelimutu from orbit: the two adjoining craters and the third apart, the summit road and car park below. Colours in this image are those of one dry-season day; they change."},
                {"name": "Detusoko", "image": "detusoko-terraces", "text": "Terraced paddies, a small river and a suspension bridge on the Ende to Moni road, about 20 kilometres short of Moni."},
                {"name": "Nggela's coast", "image": "nggela-coast", "text": "The ridge village and its single-track road above the south coast. The Wolojita coast road is known to be cut by landslides after heavy rain; frequency unknown."},
                {"name": "Koka", "image": "koka-beach", "text": "The twin coves and their headland, about 48 kilometres west of Maumere. The private access spur charges small fees at up to two checkpoints; whether cyclists pay is unconfirmed."},
            ],
            "practical": {
                "water": "Reliable at Ende, Detusoko and Moni; unreliable at Nggela and Koka. Carry from Moni for the weaving villages.",
                "resupply": "Full at Ende; basic at Detusoko and Moni (last reliable before the coast); minimal at Wolojita and Nggela; warungs at Koka and Paga.",
                "sleep": "Guesthouses in Moni (limited, book ahead in season); homestays at Detusoko, Wolojita and Nggela; nothing at the summit or the beaches.",
                "protocol": "Mandatory dawn stop at Kelimutu; national park fee. Wolotopo, Wologai and Nggela are adat villages: accompanied visits, betel or donation, guest book, council agreement for a checkpoint.",
                "hazards": "Volcanic gas and crater-wall instability at Kelimutu; cold and wind before dawn; landslides on the Wolojita coast road; the final approach to the lakes is stairs, carried not ridden.",
            },
            "scouting": [
                "Checkpoint agreements, above all with Nggela.",
                "How often the Wolojita coast road is cut, and the detour.",
                "Field coordinates for Paga and Koka; a landslide-free line between the weaving villages and the beaches.",
            ],
            "options": [],
        },
        {
            "id": "sec-09-sikka-portuguese",
            "order": 9,
            "title": "Sikka and the Portuguese south",
            "subtitle": "A wooden church from 1899, a kingdom that kept its rajas, and the town the sea rebuilt",
            "anchors_line": "Koka → Sikka village → Lela → Maumere",
            "hero": "sikka-lela",
            "lede": "The quiet older half of the Portuguese story that the finish town will complete.",
            "story": [
                "Sikka village gave its name to the regency and to a royal line, the Ximenes da Silva, whose descendants still live here: a kingdom whose rulers converted under Portuguese and Dominican influence in the sixteenth and seventeenth centuries and kept real authority into the twentieth, long after Portugal ceded the coast to the Dutch in 1859. Its wooden church of St Ignatius Loyola, begun in 1896 and first used for Mass on Christmas Eve 1899, blends a European Baroque form with ikat-motif interior decoration and teak shipped from Java. Every Good Friday the village carries a crucifix said to be a royal heirloom through the streets in the Logu Senhor procession. Sikka weavers make some of the island's most elaborate ikat, dark palettes with sailors, boats, shrimp and crabs from a seafaring ancestry.",
                "Lela, the next sub-district capital along the coast, is a secondary seat of the same mission and a natural link into Maumere; a nineteen-metre Mary of All Nations statue stands on a hill in the area, its exact position relative to the route still to be confirmed. Nine kilometres inland from Maumere, on a hilltop, is Ledalero: St Paul's Major Seminary, founded in 1937 by the Divine Word Missionaries, one of the largest Catholic seminaries in the world, which has formed close to 1,500 missionary priests.",
                "Maumere is the largest town of eastern Flores and the section's finish: airport, the TC Hillers hospital, market, hotels, a natural rest day before the hardest logistics of the race. At half past five in the morning on 12 December 1992 a magnitude 7.7 earthquake off the north coast sent tsunami waves ashore within minutes, killing about 2,000 people, some 700 of them on Babi island where the run-up reached 26 metres. The town's young building stock is that legacy. On the way in, Wuring is a Bajo, or mixed Bajo and Bugis, village built on stilts over the tidal flats, plank walkways instead of streets, boats under the houses: a working community to ride through slowly and respectfully, not a checkpoint.",
            ],
            "places": [
                {"name": "Sikka and Lela", "image": "sikka-lela", "text": "The south-coast curve between the two mission villages. The road is generally good; no lodging confirmed in Sikka itself."},
                {"name": "Maumere and Wuring", "image": "maumere-wuring", "text": "The bay, the town, the stilt village on the western flats, Frans Seda airport to the east. No dedicated bicycle shop was found anywhere on Flores; carry spares."},
            ],
            "practical": {
                "water": "Reliable at Maumere; unreliable at Koka, Sikka and Lela.",
                "resupply": "Warungs at Koka and Paga; basic at Lela; full at Maumere.",
                "sleep": "Homestay at Sikka; hotels at Maumere.",
                "protocol": "Active parish and royal graves at Sikka: greet before photographing, courtesy donation at the church. Ledalero is a working seminary. Wuring: ride slowly, ask before photographing, dress modestly.",
                "hazards": "Coastal heat; town traffic in Maumere; earthquake and tsunami awareness for the whole north coast.",
            },
            "scouting": [
                "Any bicycle spares or mechanic in Maumere?",
                "Position of Bukit Nilo relative to Lela and the route.",
                "Whether cyclists pay the Koka access toll, and how much.",
            ],
            "options": ["opt-bola-coast"],
        },
        {
            "id": "sec-10-egon-far-east",
            "order": 10,
            "title": "Egon and the far east",
            "subtitle": "Weavers, an active crater, a mangrove coast, the crux of the race and a finish under an ancestral mountain",
            "anchors_line": "Maumere → Watublapi → Egon (Blidit) → Waiterang → Talibura → north of Lewotobi → Larantuka",
            "hero": "lewotobi-twins",
            "lede": "Spectacular and dangerous are the same fact here. The route is designed around it.",
            "story": [
                "Eighteen kilometres south-east of Maumere, Watublapi is the most arrangeable cultural stop of the whole course: not an adat village to be petitioned but a weavers' cooperative, Sanggar Bliran Sina, founded in the 1980s with the help of a German priest, now more than forty members who spin local cotton, dye it with indigo and morinda from their gardens, tie the resist patterns and weave on back-strap looms, and welcome groups with dance and music by arrangement. Buying cloth is how a visiting group says thank you.",
                "Egon is the far east's hike-a-bike: an active volcano of about 1,661 to 1,703 metres, sources disagree, with an acid crater lake and fumaroles, climbed from an unsigned trailhead beyond Blidit at about 790 metres, roughly four hours up through forest onto bare slopes and four down. It reawakened in 2004, forcing 7,000 people off its flanks, and has been quiet at Level I since; a river hot spring five kilometres along the access road is the reward for those who do not summit. Then the black-sand coast at Waiterang and Wodong, small dive resorts and Pulau Babi offshore, and Talibura, a mangrove-fringed village that is the last basic resupply before the longest push of the race.",
                "Lewotobi Laki-laki, 1,584 metres, and Lewotobi Perempuan, 1,703 metres, two kilometres apart, have been in violent eruption since 3 November 2024, when the first eruption of the crisis killed nine or ten people and displaced more than 10,000. The alert reached the maximum Level IV more than once, most recently in September 2025; in 2026 alone MAGMA Indonesia logged 778 eruptions by late August, the second most active volcano in the country. Ash has repeatedly closed Maumere's airport and blanketed the Trans-Flores through Talibura. As of the last week of August 2026 PVMBG held Level III with a five-kilometre exclusion radius and standing lahar warnings for named rivers. The course therefore stays on the north coast, well outside the radius, and treats the highway corridor via Boru as an alternative to be opened only by a race-week go/no-go decision against the live bulletin, with an abort rule agreed in advance. Larantuka is the finish: a Portuguese-Catholic port converted in the 1500s, where the Confreria has run the Semana Santa processions for more than four hundred years, carrying the Tuan Ma statue, found on the beach around 1510, from its chapel to the Reinha Rosari cathedral each Holy Week, and where some residents still speak a Portuguese-influenced Malay creole. Above it stands Ile Mandiri, 1,502 metres, the ancestral mountain of the old kingdom, four to five hours from Riang Kemie: the optional sting in the tail, if it can be shown safe after two weeks of racing.",
            ],
            "places": [
                {"name": "The Lewotobi twins", "image": "lewotobi-twins", "text": "Laki-laki and Perempuan from orbit, with fresh deposits and the villages on their flanks. No part of the course approaches them; any photography is long-range from the coast. Status re-checked monthly and in race week."},
                {"name": "Egon's crater", "image": "egon-crater", "text": "The crater and its lake above Blidit; the north-coast highway at Waigete below. An entry or parking fee is charged locally; the amount was not confirmed."},
                {"name": "Larantuka and Ile Mandiri", "image": "larantuka-ile-mandiri", "text": "The finish town on the strait, Adonara across the water, the cone behind. Ferries to Adonara, Solor, Lembata and Kupang; Gewayantana airport about fifteen kilometres out."},
            ],
            "practical": {
                "water": "Reliable at Maumere and Larantuka only; unreliable at Watublapi, Blidit, Waiterang and Talibura; nothing mapped between Talibura and Larantuka on the north-coast line. Full carry for the last leg.",
                "resupply": "Full at both ends; minimal at Watublapi and Blidit; basic at Talibura.",
                "sleep": "Homestay at Watublapi; dive cottages at Waiterang; nothing at Blidit or Talibura; hotels at Larantuka.",
                "protocol": "Watublapi: arrange the visit in advance, ask before photographing, buy cloth. Egon: guide or GPS track effectively required. Larantuka: church courtesy; Semana Santa itself falls at Easter, outside the race window.",
                "hazards": "Lewotobi exclusion radius and lahars in named river corridors; ash on the highway; fumaroles at Egon's rim; heat and no water on the long coastal leg; very steep ground on Ile Mandiri.",
            },
            "scouting": [
                "The realistic corridor past Lewotobi, the reroute and the abort rule, checked against PVMBG every month.",
                "Water and any resupply between Talibura and Larantuka on the north-coast line.",
                "Whether an Ile Mandiri finale can be done safely at the end of a race.",
            ],
            "options": ["opt-bola-coast", "opt-lewotobi-corridor"],
        },
    ],
    "options": {
        "heading": "Optional loops and alternatives",
        "intro": [
            "The main course is one line. Around it the data carries seven optional pieces, each routed over the same track network and each with the same honesty label: concept, unscouted. Two of them make the Ultra variant; one more makes the Ultra+. The rest are alternatives for a scouting verdict, a village decision, a volcano or a time limit. For each option the map shows the option in its own colour and the main-course stretch it would replace in dashed vermilion, and the table gives the derived numbers side by side.",
            "The concept document hoped the loops would add 120 to 250 kilometres. Routed honestly between their real endpoints they add far less; the numbers below are the ones that count.",
        ],
        "items": {
            "opt-manggarai-timur-interior": {
                "why": "Borong is a full-service regency capital on the south coast; Elar's sub-district has a forest lake with eight satellites, the Tetes Tana waterfall, Puncatiti weaving and cattle savanna; and the Elar to Pota link is the least-known stretch in the whole concept. It swaps the highland lake at Ranamese, the Liang Bua cave and the port of Reo for the interior of Manggarai Timur.",
                "when": "For the Ultra. Only after scouts have ridden Borong to Elar to Pota; no source addresses the Elar to Pota stretch at all.",
                "risks": "The same August 2026 water emergency reached posts in Borong sub-district; Elar has minimal resupply and no confirmed beds.",
            },
            "opt-bola-coast": {
                "why": "A quieter, far less documented coast on the south side of the Sikka isthmus before climbing to Watublapi and Egon. Bola is itself a weaving village, with the Watu Krus stone cross on its seafront.",
                "when": "For the Ultra, or for any edition that wants one more coast before the far east.",
                "risks": "Unscouted road, minimal resupply, unreliable water at Bola.",
            },
            "opt-inerie-circuit": {
                "why": "Rounds the whole cone instead of crossing its shoulder: Bena to the rebuilt village of Gurusina, down the wild southern slope to the sea at Sewowoto, where waves spray through the rocks at Ena Bhara beach, then the coast road west to Aimere. Two more cultural stops and a coastal payoff, with far less estimated hike-a-bike than the shoulder.",
                "when": "For the Ultra+, or as the main line if the shoulder descent proves unsafe with a loaded bike.",
                "risks": "The two legs south of Gurusina carry the maximum remoteness index in the data and nobody has scouted them; strong currents at the beach; no beds or water between Gurusina and Aimere.",
            },
            "opt-wae-rebo-out-and-back": {
                "why": "If the onward trail from Wae Rebo cannot be done with a bike, riders climb to the village, return by the same path to Denge and ride the remote-profile road to Todo. Almost the same distance as the main line, the same village, honest about the trail.",
                "when": "The default until scouts have walked the onward trail; every trekking account uses the Denge path both ways.",
                "risks": "Descending the steep porters' steps with a loaded bike; timing the village welcome and the return in one day.",
            },
            "opt-boawae-nangaroro-direct": {
                "why": "Cross from Boawae straight over the spine to the south coast at Nangaroro and skip Mbay and the Aesesa plain. Much shorter and less remote.",
                "when": "A time-limit fallback, a heat or water contingency, or a shorter edition.",
                "risks": "Drops the rice plain and Mbay's full resupply; Nangaroro's water is unreliable at the far end.",
            },
            "opt-south-coast-aimere-nangaroro": {
                "why": "Stay on the remote south coast of Ngada and Nagekeo from Aimere all the way to Nangaroro instead of climbing back to the plateau. High remoteness, roughly 36 metres of climbing per kilometre on tertiary and village roads, grey-stone beaches at Tonggo with coconut palms and thatched shelters.",
                "when": "A coast-hugging variant for an edition that has already made the plateau's cultural stops on another day, or for a shorter race.",
                "risks": "Drops Mataloko, Wogo, Ebulobo, Boawae and Mbay, the section's whole volcano and highland-village content; weak resupply and unreliable water at both ends and nothing confirmed between.",
            },
            "opt-lewotobi-corridor": {
                "why": "The Trans-Flores corridor south of the twin volcanoes through Boru, the sub-district capital with roadside restaurants and a PVMBG observation post. Shorter to plan, longer as routed, and inside the zone that ash has closed repeatedly.",
                "when": "Only if PVMBG's alert level and exclusion radius allow it on race day, decided in race week against the live bulletin, with the north-coast line as the primary and an abort rule agreed in advance.",
                "risks": "Everything that section 10 says about Lewotobi: eruptions, ash on the road, lahars in the river corridors, a radius that has been 4, 5 and 8 kilometres within a single year.",
            },
        },
        "considered": [
            ("A Kelimutu to Egon highland link", "Computes at 120 to 163 kilometres with 4,700 to 7,300 metres of climbing and would drop the Lio weaving villages, the Paga and Koka beaches, Sikka and Maumere. It contradicts the cultural priority, so it is recorded in the data and not offered."),
            ("Riung to Mbay along the north coast", "Computes at 48 kilometres with the lowest remoteness index on the course: a paved main road. No adventure value on its own; it would only make sense inside a re-ordered Ngada section."),
            ("An Adonara or Lembata epilogue by ferry", "Named in the concept as a way to reach 1,600 kilometres or more. Ferries from Larantuka to Adonara, Solor and Lembata exist and are unreliable; not built as segments, and not on Flores."),
        ],
    },
    "hazards": {
        "heading": "Hazards and constraints",
        "intro": "Flores is volcanically and seismically alive, hot on its coasts and cold on its ridges, and it carries malaria. None of this argues against the race; all of it argues for dated information, pre-agreed rules and a medical plan. Volcano statuses below are the last confirmed as of early September 2026 and must be re-read from PVMBG and MAGMA Indonesia monthly and in race week.",
        "volcanoes": [
            ("Lewotobi Laki-laki / Perempuan", "1,584 / 1,703 m", "Level III, 5 km exclusion, lahar warnings (27 Aug–2 Sep 2026); Level IV at times in 2024–2025; 778 eruptions in 2026 by 27 Aug", "Section 10: no-go zone; north-coast corridor primary; Boru corridor gated by a race-week decision"),
            ("Iya (Ende)", "637 m", "Level II, 2 km stay-away radius (through June 2026); Level III Nov 2024 to Jan 2025", "Section 7: no course dependency on the southern peninsula; re-check before Ende"),
            ("Kelimutu", "1,639 m", "Level I; middle-lake temperature rose 28 to 35 °C in June 2026; crater-wall slide Jan 2026 judged weathering", "Section 8: mandatory dawn stop; no rim approach, no camping, regardless of level"),
            ("Ebulobo", "2,124 m", "Level I in the last public round-ups; summit-area landslides after the 15 Aug 2026 M7.7 earthquake, no rise in activity", "Section 6: course rounds the base; summit is optional and guided"),
            ("Egon", "1,661–1,703 m", "Level I; reawakened 2004 (7,000 evacuated), last notable emission cited 2008", "Section 10: optional hike-a-bike gated by status; no lingering at fumaroles"),
            ("Inerie", "2,245 m", "Not on active alert lists; last reported smoke 1911", "Section 5: hazard is the loose, exposed hike-a-bike terrain, not eruption"),
            ("Wai Sano", "903 m", "No confirmed Holocene eruption; hot springs and solfataras active", "Section 1: context only"),
            ("Ile Mandiri", "1,502 m", "Dormant, not actively monitored", "Section 10: optional finale; steepness and fatigue are the hazard"),
            ("Rokatenda (Palue)", "875 m", "Episodic unrest, fatal eruption 2013; offshore", "Context for the north coast; not on the course"),
        ],
        "other": [
            ("Earthquakes and tsunami", "The 12 December 1992 M7.7 earthquake and tsunami killed about 2,000 people around Maumere and on Babi island, with a 26-metre run-up at Riang-Kroko. On 15 August 2026 a M7.7 earthquake 68 kilometres north-north-west of Ende killed at least 47 people, damaged hundreds of houses in Nagekeo and produced more than 230 aftershocks; a tsunami warning was lifted the same day. Check road and bridge damage reports in Nagekeo before planning near Boawae; carry a tsunami awareness note for the whole north coast."),
            ("Water and heat", "The north coast and the Nagekeo interior were on emergency water trucking in August 2026. Mandatory carry capacity, coasts ridden early and late, a heat-illness plan, planned water points only where unavoidable."),
            ("Malaria and dengue", "East Nusa Tenggara is among Indonesia's highest-malaria provinces; Sikka regency was named among the concentrations in 2023, while several Flores districts hold elimination certificates. Prophylaxis advice from a travel clinic, repellent, nets at checkpoints, and symptom awareness in the briefing."),
            ("Season", "Late June to September is the dry, cooler south-east monsoon; August is the driest month. Coastal nights around 19 to 20 °C, highland towns noticeably colder; Ruteng averages about 16 °C. Landslides carry from the wet season into early dry season on cut slopes."),
            ("Animals", "Free-roaming village dogs everywhere on course (standard bikepacking advice, rabies pre-exposure vaccination to be considered). Saltwater crocodiles are documented on Flores' coasts, including a fatality in West Manggarai: no wading or swimming at river mouths, mangroves or estuaries, especially at dawn and dusk. Komodo dragons are on the islands, not on the course."),
            ("Roads", "The Trans-Flores is used only for short links and never at night in towns; ash has reduced visibility on it through Talibura, Ile Bura and Titehena during eruptive phases. Off the highway, road quality is often poor and better suited to motorbikes than cars, which is the point."),
        ],
    },
    "culture": {
        "heading": "Cultural threads and protocol",
        "intro": "The course is built to carry a handful of stories from one end of the island to the other. They are also the reason the race must arrive as a guest.",
        "threads": [
            ("Deep time", "Liang Bua, Mata Menge", "A one-metre-tall human relative excavated in 2003, dated to 60,000 to 100,000 years; and, in the So'a basin, a jaw and teeth from about 700,000 years ago. Flores was an island of its own evolution long before anyone now living."),
            ("The megalithic present", "Bena, Luba, Tololela, Gurusina, Wogo; Wae Rebo, Todo; Cancar", "Ngadhu and bhaga shrines, one pair per clan; conical mbaru niang houses; spider-web fields divided from a centre. Living social orders made visible in stone, thatch and rice."),
            ("Weaving", "Nggela, Jopu, Wolojita; Watublapi; Manggarai songke", "Three living ikat traditions: Lio, Sikka and Manggarai. Back-strap looms, resist-tied thread, natural dyes where they survive (Watublapi still uses them; the coastal Lio villages mostly do not). Buying cloth is the honest way to support a village."),
            ("Fire and souls", "Kelimutu; every volcano on the route", "The three lakes as the sorting place of the dead in Lio belief, fed every 14 August at Pati Ka. Ile Mandiri as the ancestor of the Larantuka kingdom. Inerie faced by every shrine beneath it."),
            ("Portugal and Rome", "Sikka, Lela, Ledalero, Larantuka, Solor", "A Dominican stone fort on Solor in 1566; a wooden church at Sikka in 1899; a seminary at Ledalero that has formed 1,500 priests; five centuries of Semana Santa at Larantuka. More than four in five people on Flores are Catholic."),
            ("The republic", "Ende", "Sukarno's exile years, 1934 to 1938, and the breadfruit tree where the Pancasila is said to have been shaped."),
            ("Combat as ritual", "Cancar and Manggarai (caci); Boawae (Etu)", "Whip-and-shield fighting at the Penti harvest festival; one-handed boxing in palm-fibre gloves in the Nagekeo harvest cycle in June and July. Attended only by consent, never staged."),
            ("Sea people", "Wuring; the Bajo coast", "A stilt village of Bajo and Bugis families over the tidal flats of Maumere bay, one of very few on an island of highland farmers."),
        ],
        "etiquette": [
            "Arrive slowly and greet the elders or the head of the household before anything else; a checkpoint in a village exists because the council said yes.",
            "Sign the guest book and leave the donation or contribution the village has set; where betel (sirih) is offered, accept it.",
            "Ask before photographing people, house interiors, ceremonies or the shrines; some structures are restricted.",
            "Dress modestly in villages and churches; no swimwear away from the beach.",
            "No naked flames, stoves or smoking near thatched houses. Gurusina lost 27 houses in one evening in 2018; Wologai lost 22 in 2012.",
            "Buy cloth, food and beds from the village itself; that income is the reason the race is welcome.",
            "Working communities that have not agreed to host (Wuring, the seminaries, the geothermal villages) are passed through, quietly, not treated as checkpoints.",
        ],
    },
    "logistics": {
        "heading": "Logistics",
        "intro": "A thin, well-serviced spine of five small airports, one paved highway, six full-resupply towns with hospitals, and how quickly it thins once the course leaves it.",
        "airports": [
            ("Labuan Bajo, Komodo (LBJ)", "The start. Denpasar four to six times a day, Jakarta with five airlines, Lombok, Kuala Lumpur; Singapore service in flux in 2025–2026. The only hospital in West Manggarai is here (Siloam)."),
            ("Ende, H. Hasan Aroeboesman (ENE)", "Two kilometres from town; Wings Air to Kupang and Labuan Bajo. Mid-course medical evacuation point."),
            ("Bajawa, Turelelo-Soa (BJW)", "Twenty-four kilometres north of Bajawa; flights to Kupang and Ende."),
            ("Maumere, Frans Seda (MOF)", "Five kilometres from town; Wings Air and Nam Air to Kupang, Labuan Bajo, Makassar. Repeatedly closed by Lewotobi ash, once from July to December 2024."),
            ("Larantuka, Gewayantana (LKA)", "About fifteen kilometres out; regional carriers from Kupang. Shares the eruption-driven suspensions."),
        ],
        "ferries": [
            ("Labuan Bajo – Sape (Sumbawa)", "The classic overland link from Bali; current timetable not confirmed."),
            ("Aimere – Waingapu (Sumba) / Kupang", "ASDP, Tuesdays and Fridays to Sumba per the curated data."),
            ("Mbay (Marapokot) – Palue / Kewapante", "Small ASDP links along the north coast."),
            ("Larantuka – Adonara / Solor / Lewoleba / Kupang", "KMP Ile Labalekan and KMP Ile Mandiri on multi-day rotations; cancellations happen. No direct ferry back to Labuan Bajo: onward travel from the finish is by air."),
        ],
        "hubs": [
            ("Labuan Bajo", "Full resupply, supermarkets, ATMs, Siloam hospital, motorbike mechanics; no bicycle shop found."),
            ("Ruteng", "Full resupply, market, RSUD Ruteng, many homestays; cold nights at 1,200 m."),
            ("Bajawa", "Full resupply, market, ATMs, regional hospital."),
            ("Ende", "Full resupply, RSUD Ende, airport; bicycle dealers listed in directories on Jalan Kemakmuran and Jalan Kelimutu, unconfirmed."),
            ("Maumere", "Full resupply, TC Hillers hospital, airport; motorbike repair, no bicycle shop confirmed."),
            ("Larantuka", "Full resupply, RSUD Larantuka, airport, port."),
        ],
        "money": [
            "Telkomsel has the most reliable coverage on Flores; Indosat is a cheaper second choice in towns.",
            "ATMs in the six hub towns and a few sub-district capitals; cash everywhere else.",
            "Visa on arrival about USD 35 for 30 days, with a 2026 increase proposed; Komodo park fees and quotas changed in 2026: quote current figures, not these.",
            "Homestays and guesthouses in villages run roughly IDR 150,000 to 450,000 a night where they exist; book Moni ahead in season.",
        ],
        "format": [
            ("Reference", "The Silk Road Mountain Race: about 2,050 km and 35,000 m of climbing in 2026, a 14-day limit, three staffed checkpoints, fully self-supported, a field of around 130."),
            ("Flores", "One stage, fixed route, self-supported, mandatory checkpoints of which several are cultural, roughly two weeks, late June to September. The numbers on the following pages are the course's own, derived from the routed geometry."),
        ],
    },
    "photos": {
        "heading": "Photographs to source",
        "intro": "The satellite imagery in this brochure is Copernicus Sentinel-2 data, chosen for the least cloud over each place in the 2025 and 2026 dry seasons. Ground photographs could not be gathered in the environment that produced this document (every photo host was unreachable), so each place below carries the subjects worth shooting and the search terms most likely to find openly licensed photographs on Wikimedia Commons or Flickr. Credit and licence must travel with every image used.",
    },
    "sources": {
        "heading": "Data, method and sources",
        "data": [
            "Course geometry: data/segments.geojson and data/routes.json in the project repository, routed over the Overture Maps road network (OpenStreetMap-derived) with the remote cost profile; anchors from data/nodes.geojson; places from data/pois.geojson with their own confidence and sources.",
            "Elevation: SRTM 1 arc-second tiles (USGS), sampled every 50 m, median-and-mean smoothed, 10 m hysteresis threshold for climbing; bathymetry clamped to sea level.",
            "Maps: rendered by pipeline/render_brochure_maps.py; relief from SRTM, coastline, lakes and roads © OpenStreetMap contributors via Overture Maps.",
            "Imagery: contains modified Copernicus Sentinel data 2025–2026, processed by ESA; cloud-optimised GeoTIFFs from the AWS Open Data registry (Element 84).",
            "Desk research: a search pass in September 2026 over travel, news, official (PVMBG, MAGMA Indonesia, BNPB, USGS, GVP) and academic sources, recorded with confidence labels in the project's working files; volcano and earthquake facts are dated in the text.",
        ],
        "caveats": [
            "Every segment is concept status. Distances and climbing will change with scouted GPS tracks; the climbing threshold is a design choice still to be calibrated.",
            "Track and path share on most computed pairs is low because OpenStreetMap knows Flores' roads far better than its footpaths. The remoteness the course is after may exist where the map is empty; only feet on the ground will tell.",
            "Fees, opening hours and prices are those reported in 2025–2026 and are indicative.",
        ],
    },
}
